import images from "./images";

export default [
  {
    id: 0,
    brand: "Levis",
    name: "Pantlon en jean",
    shipping: "frais de port: gratuit",
    price: 145,
    reduction: 79,
    image: images[0],
    isWished: false,
  },
  {
    id: 1,
    brand: "Vans",
    name: "Pantalon blanc",
    shipping: "frais de port: gratuit",
    price: 35.7,
    reduction: 25.8,
    image: images[1],
    isWished: false,
  },
  {
    id: 2,
    brand: "Camaieu",
    name: "Veste noir",
    shipping: "frais de port: gratuit",
    price: 175,
    reduction: 85.15,
    image: images[2],
    isWished: false,
  },
  {
    id: 3,
    brand: "Etam",
    name: "Robe blue",
    shipping: "frais de port: gratuit",
    price: 75.7,
    reduction: 35.8,
    image: images[3],
    isWished: false,
  },
  {
    id: 4,
    brand: "Naf naf",
    name: "Robe chic",
    shipping: "frais de port: gratuit",
    price: 79,
    reduction: 39.9,
    image: images[4],
    isWished: false,
  },
  {
    id: 5,
    brand: "Zara",
    name: "Robe noire",
    shipping: "frais de port: gratuit",
    price: "83",
    reduction: "65.50",
    image: images[5],
    isWished: false,
  },
  {
    id: 6,
    brand: "Nike",
    name: "Air Max",
    shipping: "frais de port: gratuit",
    price: "120",
    reduction: "95",
    image: images[6],
    isWished: false,
  },
  {
    id: 7,
    brand: "Vans",
    name: "Old school platform",
    shipping: "frais de port: gratuit",
    price: "75",
    reduction: "23.99",
    image: images[7],
    isWished: false,
  },
  {
    id: 8,
    brand: "New Balance",
    name: "Chaussure gris",
    shipping: "frais de port: gratuit",
    price: "128",
    reduction: "100",
    image: images[8],
    isWished: false,
  },
  {
    id: 9,
    brand: "A.P.C",
    name: "Stripped sweater",
    shipping: "frais de port: gratuit",
    price: "150",
    reduction: "83.50",
    image: images[9],
    isWished: false,
  },
  {
    id: 10,
    brand: "",
    name: "",
    shipping: "frais de port: gratuit",
    price: "",
    reduction: "",
    image: images[10],
    isWished: false,
  },
  {
    id: 11,
    brand: "",
    name: "",
    shipping: "frais de port: gratuit",
    price: "",
    reduction: "",
    image: images[10],
    isWished: false,
  },
];
